#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#include "../../config.h"

#define B7_AUDIO
#define AUDIO_CLICKY
#define AUDIO_CLICKY_ON

#define AUDIO_CLICKY_FREQ_DEFAULT 0.0f
#define AUDIO_CLICKY_FREQ_MIN AUDIO_CLICKY_FREQ_DEFAULT
#define AUDIO_CLICKY_FREQ_MAX AUDIO_CLICKY_FREQ_MIN
#define AUDIO_CLICKY_FREQ_FACTOR 0.0f
#define AUDIO_CLICKY_FREQ_RANDOMNESS 0.0f

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2 // Nr of taps before toggling to layer -- TT()

#define MOUSEKEY_INTERVAL       20
#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    15
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      7
#define MOUSEKEY_WHEEL_DELAY 0


#endif
